Bootstrap: docker
From: debian:buster-slim

%environment
    export LC_ALL=C.UTF-8

%runscript
    exec "/usr/local/bin/oncodrivefml" "$@"

%post

    # Load environment
    export LC_ALL=C.UTF-8

    # Install dependencies
    apt update
    apt install -y python3.6 python3-pip python3-configobj python3-numpy python3-scipy python3-pycurl libz-dev \
                   python3-statsmodels python3-pandas python3-matplotlib python3-click cython3 python-jinja2

    # Install OncodriveFML
    pip3 --no-cache-dir install oncodrivefml

    # Clean unused things
    apt remove -y python3-pip
    apt autoremove -y
    rm -rf /var/lib/apt/lists/*
