Bootstrap: docker
From: debian:buster-slim

%environment
    export LC_ALL=C.UTF-8

%runscript
    exec "/usr/local/bin/oncodriveclustl" "$@"

%post

    # Load environment
    export LC_ALL=C.UTF-8

    # Install dependencies
    apt update
    apt install -y git python3.6 python3-pip python3-sklearn python3-statsmodels \
                   python3-matplotlib python3-scipy python3-pandas python3-numpy python3-pycurl \
                   python3-click python3-requests python3-tqdm python3-daiquiri python3-humanize \
                   python3-certifi python3-configobj python3-sortedcontainers

    # Install OncodriveCLUSTL
    pip3 --no-cache-dir install git+https://bitbucket.org/bbglab/oncodriveclustl.git@master

    # Clean unused things
    apt remove -y python3-pip git
    apt autoremove -y
    rm -rf /var/lib/apt/lists/*
