Bootstrap: docker
From: continuumio/miniconda3:4.5.12

%environment
    export LC_ALL=C.UTF-8

%runscript
    exec "/mutrate/pipeline.sh" "$@"

%setup
    mkdir ${SINGULARITY_ROOTFS}/mutrate
    cp -r *.py ${SINGULARITY_ROOTFS}/mutrate/
    cp -r *.sh ${SINGULARITY_ROOTFS}/mutrate/
    cp -r *.r ${SINGULARITY_ROOTFS}/mutrate/
    chmod -R a+rx ${SINGULARITY_ROOTFS}/mutrate/

%post

    # Load environment
    export LC_ALL=C.UTF-8

    apt update
    apt install -y wget build-essential
    rm -rf /var/lib/apt/lists/*

    # Install dependencies
    /opt/conda/bin/conda install -y -c r -c conda-forge python=3.6 numpy pandas tqdm dill click pathos r-essentials r-devtools r-docopt r-rcpp=0.12 r-coda r-codetools r-rstan=2.17 r-clue
    
    # Install Sigfit
    cd /root
    wget https://github.com/kgori/sigfit/archive/v1.0.0.tar.gz
    tar xvzf v1.0.0.tar.gz
    echo "devtools::install(\"/root/sigfit-1.0.0\", args = \"--preclean\", dependencies = FALSE)" | /opt/conda/bin/R --no-save
    rm v1.0.0.tar.gz
    rm -rf sigfit-1.0.0