Bootstrap: docker
From: debian:buster-slim

%environment
    export LC_ALL=C.UTF-8

%runscript
    exec "/mutrate/run.sh" "$@"

%setup
    mkdir ${SINGULARITY_ROOTFS}/mutrate
    cp signature_assignment.py ${SINGULARITY_ROOTFS}/mutrate/
    cp compute_mutrate.py ${SINGULARITY_ROOTFS}/mutrate/
    cp run.sh ${SINGULARITY_ROOTFS}/mutrate/
    chmod -R a+rx ${SINGULARITY_ROOTFS}/mutrate/

%post
    apt-get update
    apt-get -y install locales-all python3 python3-pip python3-numpy python3-pandas python3-click python3-tqdm
    rm -rf /var/lib/apt/lists/*
