Bootstrap: docker
From: continuumio/miniconda3:4.5.12

%environment
    export LC_ALL=C.UTF-8

%runscript
    exec "/combination/schulze.sh" "$@"

%setup
    mkdir ${SINGULARITY_ROOTFS}/combination
    cp -r src/* ${SINGULARITY_ROOTFS}/combination/
    chmod -R a+rx ${SINGULARITY_ROOTFS}/combination/

%post

    # Load environment
    export LC_ALL=C.UTF-8

    # Install Cython dependencies
    apt update
    apt install -y build-essential
    rm -rf /var/lib/apt/lists/*

    # Install Python dependencies
    /opt/conda/bin/conda install -y -c conda-forge python=3.6 pandas=0.23 numpy=1.15 click=7.0 statsmodels=0.9 cython=0.29 scipy=1.2 tqdm=4.29 configobj=5.0
