Bootstrap: docker
From: debian:buster-slim

%environment
    export LC_ALL=C.UTF-8

%runscript
    exec "/usr/local/bin/smregions" "$@"

%setup
    mkdir ${SINGULARITY_ROOTFS}/smregions
    cp -r src/* ${SINGULARITY_ROOTFS}/smregions/
    chmod -R a+rx ${SINGULARITY_ROOTFS}/smregions/

%post

    # Load environment
    export LC_ALL=C.UTF-8

    # Install dependencies
    apt update
    apt install -y python3-pip python3-configobj python3-numpy python3-scipy python3-pycurl libz-dev python3-statsmodels python3-requests \
                   python3-pandas python3-setuptools python3-click python3-intervaltree python3-tqdm python3-appdirs python3-dill

    # Install SMRegions
    cd /smregions/
    python3 /smregions/setup.py install

    # Clean unused things
    rm -rf /var/lib/apt/lists/*
