Bootstrap: docker
From: debian:buster-slim

%environment
    export LC_ALL=C.UTF-8
    export BBGLAB_HOME=/oncodrivefml
    export BGDATA_OFFLINE=TRUE

%runscript
    exec "/usr/local/bin/oncodrivefml" "$@"

%setup
    mkdir ${SINGULARITY_ROOTFS}/oncodrivefml
    cp oncodrivefml_v2.conf ${SINGULARITY_ROOTFS}/oncodrivefml/
    chmod -R a+rx ${SINGULARITY_ROOTFS}/oncodrivefml/

%post

    # Load environment
    export LC_ALL=C.UTF-8

    # Install dependencies
    apt update
    apt install -y python3.6 python3-pip python3-configobj python3-numpy python3-scipy python3-pycurl libz-dev \
                   python3-statsmodels python3-pandas python3-matplotlib python3-click cython3 python-jinja2

    # Install OncodriveFML
    pip3 --no-cache-dir install https://bitbucket.org/bbglab/oncodrivefml/get/develop.tar.gz

    # Clean unused things
    apt remove -y python3-pip
    rm -rf /var/lib/apt/lists/*
