Bootstrap: docker
From: debian:buster-slim

%environment
    export LC_ALL=C.UTF-8

%runscript
    exec "/signature/run.sh" "$@"

%setup
    mkdir ${SINGULARITY_ROOTFS}/signature
    cp run.sh ${SINGULARITY_ROOTFS}/signature/
    chmod -R a+rx ${SINGULARITY_ROOTFS}/signature/

%post
    apt-get update
    apt-get -y install locales-all python3 python3-pip python3-click python3-numpy python3-tqdm python3-pycurl

    # Install BGSignature
    pip3 install bgsignature

    rm -rf /var/lib/apt/lists/*
