Bootstrap: docker
From: alpine:3.8

%environment
    export LC_ALL=C.UTF-8
    
%runscript
    exec "/bin/sh" "/hotmaps/hotmaps.sh" "$@"

%setup
    mkdir ${SINGULARITY_ROOTFS}/hotmaps
    cp -r scripts ${SINGULARITY_ROOTFS}/hotmaps/
    cp hotmaps.sh ${SINGULARITY_ROOTFS}/hotmaps/
    chmod -R a+r ${SINGULARITY_ROOTFS}/hotmaps/

%post
    apk add --no-cache python-dev py-pip py-curl zlib-dev make ncurses-dev g++
    pip --no-cache-dir install pandas tqdm futures bgreference biopython pyliftover