

CONTAINER_DECONSTRUCTSIGS = $(CONTAINERS)/deconstructsig.simg

SRC_CONTAINER_DECONSTRUCTSIGS = ${CONTAINERS_SOURCE_FOLDER}/deconstructsig

CONTAINER_DECONSTRUCTSIGS_FILES = $(wildcard ${SRC_CONTAINER_DECONSTRUCTSIGS}/*)

$(CONTAINER_DECONSTRUCTSIGS): ${CONTAINER_DECONSTRUCTSIGS_FILES} | $(CONTAINERS)
	@echo Building deconstructsig container
	cd ${SRC_CONTAINER_DECONSTRUCTSIGS} && \
		sudo singularity build $$(basename $@) Singularity
	mv ${SRC_CONTAINER_DECONSTRUCTSIGS}/$$(basename $@) $@
	sudo chown ${USER}: $@

TARGETS_CONTAINERS_SUDO += $(CONTAINER_DECONSTRUCTSIGS)