Bootstrap: docker
From: debian:buster-slim

%runscript
    exec "/usr/bin/python3" "/deconstructsig/assign_signature_to_mutation.py" "$@"

%setup
    mkdir ${SINGULARITY_ROOTFS}/deconstructsig
    cp assign_signature_to_mutation.py ${SINGULARITY_ROOTFS}/deconstructsig/
    cp deconstructSigs.r ${SINGULARITY_ROOTFS}/deconstructsig/
    chmod -R a+rx ${SINGULARITY_ROOTFS}/deconstructsig/

%post
    apt-get update
    apt-get install -y python3-pandas r-bioc-bsgenome r-cran-gplots
    rm -rf /var/lib/apt/lists/*
    echo "install.packages(\"BiocManager\", repos=\"https://cran.r-project.org\")" | R --no-save
    echo "BiocManager::install(\"BSgenome.Hsapiens.UCSC.hg19\")" | R --no-save
    echo "BiocManager::install(\"BSgenome.Hsapiens.UCSC.hg38\")" | R --no-save
    echo "install.packages(\"deconstructSigs\", repos=\"https://cran.r-project.org\")" | R --no-save

